# Generated by Django 2.2.5 on 2019-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='media/None/no-doc.pdf', upload_to='media/'),
        ),
    ]
