# Generated by Django 2.2.5 on 2019-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0002_auto_20190909_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(default='media/None/no-doc.png', upload_to='media/'),
        ),
    ]
